### ISSUE TITLE
Crash with Hardcore Ender Expansion

### ISSUE THREAD

**Issue by Shahelion** [BrassGoggledCoders/BrassUtils#43]
https://gist.github.com/Zsashas/d68533f64dafecdac233e6ab8cb9a0ec

**Comment by FreneticScribbler** [comment]
Does this custom build fix it? (not easy for me to test)

http://www.mediafire.com/download/deb4ig2h9m3t7ho/brassutils-1.0.1a.jar

**Comment by Shahelion** [comment]
Not entirely sure what triggered it, supposedly something broken dropped from an Enderman. My player is currently in the End, so we'll see if it crashes again when I get back into the world and I resume my Enderman hunting spree.

**Comment by Shahelion** [comment]
Since whatever item triggered it wouldn't be a guaranteed drop, and it seems fine for now, I'll close it unless I get the same crash. Consider it solved for now, I guess!
